### ISSUE TITLE
Extend streak evaluation period to 3 AM

### ISSUE THREAD

**Issue by branhoff** [branhoff/hooter-the-tutor#10]
# Extend streak evaluation period to 3 AM

## Description
Currently, our streak evaluation period ends at midnight. However, many users study late into the night. To accommodate these night owls and provide a more flexible system, we should extend the streak evaluation period to 3 AM.

## Objectives
- Allow users to maintain their streaks by studying until 3 AM
- Increase flexibility for users with different study schedules
- Potentially increase user engagement and streak maintenance

## Tasks
- [ ] Modify the streak calculation logic to consider the extended time period
- [ ] Update the daily streak reset timing from midnight to 3 AM
- [ ] Adjust any related time-based functions or scheduled tasks
- [ ] Update user-facing messages and documentation to reflect the new evaluation period
- [ ] Implement a transition plan for existing streaks
- [ ] Add appropriate logging for the new evaluation period

## Implementation Details
1. Update the `process_streak` function in `streaks.py` to consider the extended time
2. Modify any scheduled tasks that run at midnight to run at 3 AM instead
3. Ensure that streaks are not double-counted across days

## Example Logic
```python
def is_within_evaluation_period(time):
    # Check if the given time is before 3 AM of the next day
    next_day_3am = (datetime.now() + timedelta(days=1)).replace(hour=3, minute=0, second=0, microsecond=0)
    return time < next_day_3am
```

## Benefits
- More inclusive of different study schedules
- Potential increase in user engagement and streak maintenance
- Aligns better with typical student behavior

## Potential Risks
- May confuse users initially about when the "day" ends for streak purposes
- Slight increase in complexity of streak calculation logic

## Additional Notes
- Consider adding a user setting to choose their preferred "day end" time in the future

## Definition of Done
- Streak evaluation period successfully extended to 3 AM
- All related functions and tasks updated accordingly
- User documentation updated
- Transition plan implemented for existing streaks
- Feature thoroughly tested, including edge cases (e.g., studying from 11 PM to 2 AM)
- Code review completed and approved
