### ISSUE TITLE
Create a development Discord environment for local bot testing

### ISSUE THREAD

**Issue by branhoff** [branhoff/hooter-the-tutor#14]
# Create a development Discord environment for local bot testing

## Description
To facilitate easier testing and development of new features, we need to set up a separate development environment for our Discord bot. This environment should allow developers to run and test the bot locally without interfering with the production bot. Additionally, the development bot should be easily distinguishable from the production bot to avoid confusion.

## Objectives
- Create a separate Discord server for development and testing
- Set up a development version of the bot that can run locally
- Ensure the development bot doesn't conflict with the production bot
- Make the development bot easily identifiable

## Tasks
- [ ] Create a new Discord server for development and testing
- [ ] Set up a new Discord application and bot user for development
- [ ] Create a separate configuration for the development bot
- [ ] Modify the bot code to support different environments (dev/prod)
- [ ] Implement visual identifiers for the development bot
- [ ] Document the process of setting up and using the development environment

## Implementation Details

1. Discord Server Setup:
   - Create a new Discord server named "Hooter Dev Environment"
   - Set up necessary channels mirroring the production environment

2. Development Bot Setup:
   - Create a new Discord application in the Discord Developer Portal
   - Generate a new bot token for the development bot
   - Invite the development bot to the new Discord server

3. Configuration:
   - Create a `config_dev.py` file for development-specific settings
   - Use environment variables or a `.env` file to store sensitive information

4. Code Modifications:
   - Modify `main.py` to support different environment configurations
   - Example:
     ```python
     import os
     from config_dev import DevConfig
     from config_prod import ProdConfig

     if os.getenv('BOT_ENV') == 'dev':
         config = DevConfig
     else:
         config = ProdConfig

     bot = commands.Bot(command_prefix=config.PREFIX)
     ```

5. Visual Identifiers:
   - Set a distinct username for the development bot (e.g., "Hooter Dev")
   - Use a different avatar for the development bot
   - Modify the bot's status to indicate it's a development version:
     ```python
     await bot.change_presence(activity=discord.Game(name="[DEV] Testing"))
     ```

6. Documentation:
   - Create a `DEV_SETUP.md` file with instructions for setting up the development environment
   - Include steps for running the bot locally and switching between dev/prod environments

## Additional Notes
- Consider implementing a visual indicator in bot responses (e.g., [DEV] prefix in messages)
- In the future, we might want to automate the setup process for new developers

## Definition of Done
- Development Discord server is set up and functional
- Development bot can be run locally without conflicting with the production bot
- Bot clearly indicates it's a development version (visually and in responses)
- Documentation for setting up and using the development environment is complete
- ?At least one other team member has successfully set up the development environment using the documentation?
