### ISSUE TITLE
Implement proper error handling within each cog

### ISSUE THREAD

**Issue by branhoff** [branhoff/hooter-the-tutor#17]
## Description
Currently, our cogs lack comprehensive error handling, which can lead to unexpected behavior and poor user experience when errors occur.

## Objectives
1. Implement global error handlers for each cog
2. Add specific error handling for individual commands
3. Improve logging for error tracking and debugging
4. Provide user-friendly error messages

## Tasks
- [ ] Implement `cog_command_error` method in each cog to handle general command errors
- [ ] Add try-except blocks in complex methods to catch and handle specific exceptions
- [ ] Implement custom exception classes for cog-specific errors if necessary
- [ ] Add error handling for API calls and external services interactions
- [ ] Implement proper logging for all caught exceptions
- [ ] Create user-friendly error messages for common error scenarios
- [ ] Add error handling for database operations (if applicable)
- [ ] Implement rate limiting error handling
- [ ] Handle Discord API errors gracefully

### Global Error Handler
For each cog, implement a `cog_command_error` method:

```python
async def cog_command_error(self, ctx, error):
    if isinstance(error, commands.CommandOnCooldown):
        await ctx.send(f"This command is on cooldown. Try again in {error.retry_after:.2f} seconds.")
    elif isinstance(error, commands.MissingRequiredArgument):
        await ctx.send(f"Missing required argument: {error.param}")
    else:
        await ctx.send("An error occurred while processing the command.")
    
    logging.error(f"An error occurred in {ctx.command}: {str(error)}")
```

### Specific Command Error Handling
For individual commands that may raise specific exceptions:

```python
@commands.command()
async def example_command(self, ctx):
    try:
        # Command logic here
        result = await self.some_operation()
    except SomeSpecificError as e:
        await ctx.send(f"A specific error occurred: {str(e)}")
        logging.error(f"SomeSpecificError in example_command: {str(e)}")
    except Exception as e:
        await ctx.send("An unexpected error occurred.")
        logging.exception(f"Unexpected error in example_command: {str(e)}")
```

## Acceptance Criteria
- All cogs have a global error handler implemented
- Each command with potential for specific errors has try-except blocks
- All caught exceptions are logged with appropriate detail
- Users receive informative, friendly messages for common error scenarios
- Sensitive information is not exposed in user-facing error messages
- Error handling does not significantly impact performance

## Additional Considerations
- Consider implementing a custom error formatting utility for consistency across cogs
- Evaluate the need for a centralized error tracking system (e.g., Sentry)
- Ensure error messages are internationalized if the bot supports multiple languages

## Resources
- [Discord.py Error Handling Documentation](https://discordpy.readthedocs.io/en/stable/ext/commands/commands.html#error-handling)
- [Python Logging Documentation](https://docs.python.org/3/library/logging.html)
