### ISSUE TITLE
Refactor bot structure to use Discord.py cogs

### ISSUE THREAD

**Issue by branhoff** [branhoff/hooter-the-tutor#8]
# Refactor bot structure to use Discord.py cogs

## Description
Currently, our bot's commands and functionality are centralized in a single `commands.py` file. To improve modularity, maintainability, and scalability, we should refactor our bot structure to use Discord.py cogs.

## Objectives
- Reorganize existing commands into logical cog modules
- Improve code organization and readability
- Facilitate easier addition of new features in the future
- Enable hot-reloading of individual cogs for easier development and maintenance

## Tasks
- [x] Create a new `cogs` directory in the project root
- [x] Refactor existing commands into appropriate cog files:
  - [ ] Create `general.py` for general-purpose commands (e.g., `reintroduce`)
  - [x] Move streak-related functionality to `streaks.py`
  - [x] Move LeetCode-related functionality to `leetcode.py`
- [x] Update the main bot file to load cogs instead of importing from `commands.py`
- [ ] #17
- [x] Update documentation to reflect the new structure
- [x] Test all functionality to ensure it works as expected after refactoring

## Implementation Details
1. Each cog should be a subclass of `commands.Cog`
2. Include a `setup` function in each cog file for easy loading
3. Use the `bot.load_extension()` method in the main file to load cogs

## Example Cog Structure
```python
from discord.ext import commands

class ExampleCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    async def example_command(self, ctx):
        await ctx.send("This is an example command in a cog!")

def setup(bot):
    bot.add_cog(ExampleCog(bot))
```

**Comment by branhoff** [comment]
Cogs evidently also include listeners which I'm calling "events" in my code. For now, I think I'm just intending to encapsulate the command logic into cogs.

https://discordpy.readthedocs.io/en/stable/ext/commands/cogs.html
